version: '3.7'

networks:
  rabbit:
    driver: bridge
  postgres:
    driver: bridge

services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: calendar
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres

  rabbit:
    image: rabbitmq:3.7.17-management
    hostname: rabbit
    container_name: rabbit
    ports:
      - '15672:15672'
      - '5672:5672'
    expose:
      - 15672
    restart: always
    volumes:
      - ./configs/rabbit.def.json:/etc/rabbitmq/definitions.json:ro
      - ./configs/rabbit.config:/etc/rabbitmq/rabbitmq.config:ro
    networks:
      - rabbit

  calendar:
    build:
      context: .
      dockerfile: ./cmd/calendar/Dockerfile
      args:
        - CONFIG_FILE_NAME=config
    container_name: calendar
    depends_on:
      - rabbit
      - postgres
    restart: on-failure
    environment:
      - WAIT_HOSTS=postgres:5432, rabbit:5672
    ports:
      - '5555:5555'
      - '7777:7777'
    expose:
      - 5555
      - 7777
    volumes:
      - ./logs/containers/:/logs/
    networks:
      - rabbit
      - postgres

  calendar_scheduler:
    build:
      context: .
      dockerfile: ./cmd/calendar_scheduler/Dockerfile
      args:
        - CONFIG_FILE_NAME=scheduler_config
    container_name: calendar_scheduler
    depends_on:
      - calendar
      - rabbit
      - postgres
    restart: on-failure
    environment:
      - WAIT_HOSTS=postgres:5432, rabbit:5672
    ports:
      - '7502:7502'
    expose:
      - 7502
    volumes:
      - ./logs/containers/:/logs/
    networks:
      - rabbit
      - postgres

  calendar_sender:
    build:
      context: .
      dockerfile: ./cmd/calendar_sender/Dockerfile
      args:
        - CONFIG_FILE_NAME=sender_config
    container_name: calendar_sender
    depends_on:
      - calendar
      - rabbit
      - postgres
    restart: on-failure
    environment:
      - WAIT_HOSTS=postgres:5432, rabbit:5672
    ports:
      - '7503:7503'
    expose:
      - 7503
    volumes:
      - ./logs/containers/:/logs/
    networks:
      - rabbit
      - postgres
