version: '3.7'

networks:
  rabbit:
    driver: bridge
  postgres:
    driver: bridge
  calendar:
    driver: bridge

services:
  integration_tests:
    build: tests
    command: 'true'
    environment:
      TESTS_AMQP_DSN: 'amqp://guest:guest@rabbit:5672/'
      TESTS_POSTGRES_DSN: 'host=postgres port=5432 user=postgres password=example dbname=postgres sslmode=disable'
      TESTS_HTTP_HOST: 'http://calendar:5555'
      WAIT_HOSTS: postgres:5432, rabbit:5672, calendar:5555
    depends_on: 
      - calendar
    links:
      - calendar
      - calendar_scheduler
      - calendar_sender
    networks:
      - rabbit
      - postgres
      - calendar

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres_test
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres

  rabbit:
    image: rabbitmq:3.7.17-management
    hostname: rabbit
    container_name: rabbit_test
    expose:
      - 15672
    restart: always
    volumes:
      - ./configs/rabbit.def.json:/etc/rabbitmq/definitions.json:ro
      - ./configs/rabbit.config:/etc/rabbitmq/rabbitmq.config:ro
    networks:
      - rabbit

  calendar:
    build:
      context: .
      dockerfile: ./cmd/calendar/Dockerfile
      args:
        - CONFIG_FILE_NAME=config.test
    hostname: calendar
    container_name: calendar_test
    depends_on:
      - rabbit
      - postgres
    restart: on-failure
    environment:
      - WAIT_HOSTS=postgres:5432, rabbit:5672
    volumes:
      - ./logs/containers/:/logs/
    networks:
      - calendar
      - rabbit
      - postgres

  calendar_scheduler:
    build:
      context: .
      dockerfile: ./cmd/calendar_scheduler/Dockerfile
      args:
        - CONFIG_FILE_NAME=scheduler_config.test
    container_name: calendar_scheduler_test
    depends_on:
      - calendar
      - rabbit
      - postgres
    restart: on-failure
    environment:
      - WAIT_HOSTS=postgres:5432, rabbit:5672
    expose:
      - 7502
    volumes:
      - ./logs/containers/:/logs/
    networks:
      - rabbit
      - postgres

  calendar_sender:
    build:
      context: .
      dockerfile: ./cmd/calendar_sender/Dockerfile
      args:
        - CONFIG_FILE_NAME=sender_config.test
    container_name: calendar_sender_test
    depends_on:
      - calendar
      - rabbit
      - postgres
    restart: on-failure
    environment:
      - WAIT_HOSTS=postgres:5432, rabbit:5672
    expose:
      - 7503
    volumes:
      - ./logs/containers/:/logs/
    networks:
      - rabbit
      - postgres
